accounts/urls.py
from django.urls import path
from . import views 

app_name ='accounts'
urlpatterns = [
	path('signup/', views.SignUpView.as_view(), name = 'signup'),	
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('',views.BlogListView.as_view(), name = 'home'),
	path('<int:pk>/', views.BlogDetailView.as_view(), name = 'detail'),
	path('new/', views.BlogCreateView.as_view(), name = 'post_new'),
	path('<int:pk>/edit/', views.BlogUpdateView.as_view(), name = 'post_edit'),
	path('<int:pk>/delete/', views.BlogDeleteView.as_view(),name= 'post_delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

class Post(models.Model):
	title = models.CharField(max_length = 200)
	author = models.ForeignKey(
		'auth.User',
		on_delete = models.CASCADE,
	)
	body = models.TextField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', args =[str(self.id)])

	

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

class SignUpView(CreateView):
	form_class = UserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'accounts/signup.html'
	

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, UpdateView,DetailView, CreateView
from django.urls import reverse_lazy
from .models import Post


class BlogListView(ListView):
	model = Post
	template_name = 'blog/home.html'


class BlogDetailView(DetailView):
	model = Post
	template_name = 'blog/post_detail.html'

class BlogCreateView(CreateView):
	model = Post
	fields = '__all__'
	template_name = 'blog/post_new.html'

class BlogUpdateView(UpdateView):
	model = Post
	template_name = 'blog/post_edit.html'
	fields = ['title','body']

class BlogDeleteView(DeleteView):
	model = Post
	template_name = 'blog/post_delete.html'
	success_url = reverse_lazy('blog:home')

templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
    <h2>Sign Up</h2>
    <form method = 'post'>
    	{{form.as_p}}
    	{% csrf_token %}
    	<button type="submit">Sign Up</button>
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}
	    Blog Django
	{% endblock title %} </title>
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/base.css' %}" >

</head>
<body>
	<div class="container">
		<header>
			<div class="nav-left">
				<h1><a href="/">Django Blog</a></h1>
			</div>
			<div class="nav-right">
				<a href="{% url "blog:post_new" %}">+ New Blog Post</a>
			</div>
		</header>
	</div>
	{% if user.is_authenticated %}
		<p>Hi {{user.username}}</p>
		<p><a href="{% url 'logout' %}">Logout</a></p>
	{% else %}
		<p>You are not logged in.</p>
		<a href="{% url "login" %}">Login</a>
	{% endif %}
		 
	<div class="container">
		{% block content %}
	    
		{% endblock content %}
	</div>
</body>
</html>

templates/blog/home.html
{% extends "base.html" %}

{% block content %}
    {% for post in object_list %}
	<div class="post-entry">
		<h2><a href="{{post.get_absolute_url }}">{{post.title}}</a></h2>
		<p>{{post.body|truncatewords:20|linebreaks}}</p>
	</div>

    {% endfor %}
{% endblock content %}

templates/blog/post_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete Post</h1>
    <form action="" method="post">
    	{% csrf_token%}
    	<p>Are you sure you want to delete "{{post.title}}"</p>
    	<input type="submit" value = "Confirm">
    </form>
{% endblock content %}

templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="post-entry">
    	<h1>{{object.title}}</h1>
    	<p>{{post.body}}</p>
    </div>
	<p><a href="{% url "blog:post_edit" object.pk %}">+ Edit Blog Post</a></p>

	<p><a href="{% url "blog:post_delete" object.pk %}">+ Delete This Post</a></p>
{% endblock content %}

templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
    <h1>Edit Post</h1>
    <form action="" method = 'post'>
    	{{form.as_p}}
    	{% csrf_token %}
    	<input type="submit" value = 'Update'>
    </form>
{% endblock content %}

templates/blog/post_new.html
{% extends "base.html" %}

{% block content %}
    <h1>New Post</h1>
    <form action="" method="post">
    	{{form.as_p}}
    	{% csrf_token %}
    	<input type="submit" value = "Save">
    </form>
{% endblock content %}